export const seedRooms = [
  {
    name: "Phòng studio ban công Thảo Điền",
    price: 6500000,
    address: "12 Đường Quốc Hương, Thảo Điền, Quận 2, TP.HCM",
    area: "Thảo Điền",
    acreage: 32,
    maxPeople: 2,
    furniture: "Máy lạnh, giường, tủ lạnh, máy giặt, bếp từ",
    description:
      "Phòng studio thoáng, ban công rộng đón gió, khu an ninh, gần trường quốc tế và siêu thị.",
    status: "Còn phòng",
    ownerName: "Nguyễn Văn A",
    ownerPhone: "0901234567",
    electricity: "3.800đ/kWh",
    water: "100.000đ/người",
    serviceFee: "150.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: true,
    washer: true,
    elevator: false,
    images: [],
  },
  {
    name: "Căn hộ mini An Phú view sông",
    price: 8200000,
    address: "45 Nguyễn Thị Định, An Phú, Quận 2, TP.HCM",
    area: "An Phú",
    acreage: 40,
    maxPeople: 3,
    furniture: "Full nội thất, bếp, máy giặt riêng, sofa",
    description: "Căn hộ mini cao cấp, view sông Sài Gòn, có hồ bơi chung cư.",
    status: "Còn phòng",
    ownerName: "Trần Thị B",
    ownerPhone: "0912345678",
    electricity: "4.000đ/kWh",
    water: "90.000đ/người",
    serviceFee: "300.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: false,
    washer: true,
    elevator: true,
    images: [],
  },
  {
    name: "Phòng trọ giá rẻ Bình Thạnh",
    price: 3200000,
    address: "78 Điện Biên Phủ, Bình Thạnh, TP.HCM",
    area: "Bình Thạnh",
    acreage: 20,
    maxPeople: 1,
    furniture: "Máy lạnh, giường tầng",
    description: "Phòng nhỏ gọn, phù hợp sinh viên hoặc người đi làm một mình.",
    status: "Còn phòng",
    ownerName: "Lê Văn C",
    ownerPhone: "0987654321",
    electricity: "3.500đ/kWh",
    water: "80.000đ/người",
    serviceFee: "50.000đ/tháng",
    hours: "Giờ giấc tự do, khóa cổng 23h",
    pet: false,
    washer: false,
    elevator: false,
    images: [],
  },
  {
    name: "Phòng đôi Quận 7 gần Lotte Mart",
    price: 4800000,
    address: "23 Nguyễn Lương Bằng, Quận 7, TP.HCM",
    area: "Quận 7",
    acreage: 25,
    maxPeople: 2,
    furniture: "Máy lạnh, giường, tủ quần áo",
    description: "Gần Lotte Mart và trường học quốc tế, khu dân cư yên tĩnh.",
    status: "Đang giữ chỗ",
    ownerName: "Phạm Thị D",
    ownerPhone: "0933445566",
    electricity: "3.700đ/kWh",
    water: "90.000đ/người",
    serviceFee: "100.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: true,
    washer: true,
    elevator: true,
    images: [],
  },
  {
    name: "Studio cao cấp Thảo Điền có hồ bơi",
    price: 9800000,
    address: "9 Xuân Thủy, Thảo Điền, Quận 2, TP.HCM",
    area: "Thảo Điền",
    acreage: 45,
    maxPeople: 2,
    furniture: "Full nội thất cao cấp, bếp điện, máy giặt riêng",
    description: "Chung cư dịch vụ, có hồ bơi và gym, phù hợp khách nước ngoài.",
    status: "Còn phòng",
    ownerName: "Ngô Văn E",
    ownerPhone: "0977889900",
    electricity: "4.200đ/kWh",
    water: "100.000đ/người",
    serviceFee: "400.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: true,
    washer: true,
    elevator: true,
    images: [],
  },
  {
    name: "Phòng gác lửng An Phú",
    price: 5200000,
    address: "156 Trần Não, An Phú, Quận 2, TP.HCM",
    area: "An Phú",
    acreage: 28,
    maxPeople: 2,
    furniture: "Máy lạnh, gác lửng, tủ bếp mini",
    description: "Phòng có gác lửng tận dụng diện tích, gần chợ An Phú.",
    status: "Đã thuê",
    ownerName: "Vũ Thị F",
    ownerPhone: "0966778899",
    electricity: "3.600đ/kWh",
    water: "85.000đ/người",
    serviceFee: "80.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: false,
    washer: true,
    elevator: false,
    images: [],
  },
  {
    name: "Phòng ban công Bình Thạnh view thoáng",
    price: 4500000,
    address: "34 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM",
    area: "Bình Thạnh",
    acreage: 24,
    maxPeople: 2,
    furniture: "Máy lạnh, giường, kệ bếp",
    description: "Ban công rộng, nhiều cửa sổ, khu dân cư an ninh có bảo vệ.",
    status: "Còn phòng",
    ownerName: "Đặng Văn G",
    ownerPhone: "0955667788",
    electricity: "3.500đ/kWh",
    water: "80.000đ/người",
    serviceFee: "70.000đ/tháng",
    hours: "Khóa cổng 22h30",
    pet: false,
    washer: false,
    elevator: false,
    images: [],
  },
  {
    name: "Căn hộ 1PN Quận 7 nội thất mới",
    price: 7300000,
    address: "88 Huỳnh Tấn Phát, Quận 7, TP.HCM",
    area: "Quận 7",
    acreage: 38,
    maxPeople: 3,
    furniture: "Full nội thất mới, bếp, máy giặt, sofa",
    description: "Căn hộ 1 phòng ngủ riêng biệt, nội thất mới 100%.",
    status: "Còn phòng",
    ownerName: "Bùi Thị H",
    ownerPhone: "0944556677",
    electricity: "3.900đ/kWh",
    water: "95.000đ/người",
    serviceFee: "250.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: true,
    washer: true,
    elevator: true,
    images: [],
  },
  {
    name: "Phòng nhỏ tiết kiệm Quận 2",
    price: 3600000,
    address: "67 Trần Não, Quận 2, TP.HCM",
    area: "Quận 2",
    acreage: 18,
    maxPeople: 1,
    furniture: "Máy lạnh, giường",
    description: "Phòng đơn giản, tiết kiệm chi phí, gần bến xe buýt.",
    status: "Còn phòng",
    ownerName: "Hồ Văn I",
    ownerPhone: "0922334455",
    electricity: "3.500đ/kWh",
    water: "75.000đ/người",
    serviceFee: "40.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: false,
    washer: false,
    elevator: false,
    images: [],
  },
  {
    name: "Phòng đôi Thảo Điền gần trường quốc tế",
    price: 6900000,
    address: "21 Thảo Điền, Quận 2, TP.HCM",
    area: "Thảo Điền",
    acreage: 30,
    maxPeople: 2,
    furniture: "Máy lạnh, giường, bàn làm việc, tủ lạnh",
    description: "Vị trí đẹp, gần trường quốc tế BIS và nhiều quán cà phê.",
    status: "Ngưng khai thác",
    ownerName: "Đỗ Thị K",
    ownerPhone: "0911223344",
    electricity: "3.800đ/kWh",
    water: "90.000đ/người",
    serviceFee: "120.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: false,
    washer: true,
    elevator: false,
    images: [],
  },
  {
    name: "Căn hộ dịch vụ Quận 7 full tiện nghi",
    price: 10000000,
    address: "5 Nguyễn Đức Cảnh, Quận 7, TP.HCM",
    area: "Quận 7",
    acreage: 50,
    maxPeople: 3,
    furniture: "Full nội thất cao cấp, bếp, máy giặt, ban công lớn",
    description: "Căn hộ dịch vụ cao cấp, có gym và hồ bơi trong tòa nhà.",
    status: "Còn phòng",
    ownerName: "Trịnh Văn L",
    ownerPhone: "0900112233",
    electricity: "4.200đ/kWh",
    water: "100.000đ/người",
    serviceFee: "500.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: true,
    washer: true,
    elevator: true,
    images: [],
  },
  {
    name: "Phòng gọn Bình Thạnh gần cầu Thị Nghè",
    price: 4100000,
    address: "10 Nguyễn Hữu Cảnh, Bình Thạnh, TP.HCM",
    area: "Bình Thạnh",
    acreage: 22,
    maxPeople: 2,
    furniture: "Máy lạnh, giường, tủ quần áo",
    description: "Gần cầu Thị Nghè, thuận tiện di chuyển vào trung tâm Quận 1.",
    status: "Đang giữ chỗ",
    ownerName: "Mai Văn M",
    ownerPhone: "0933112244",
    electricity: "3.600đ/kWh",
    water: "85.000đ/người",
    serviceFee: "60.000đ/tháng",
    hours: "Tự do giờ giấc",
    pet: false,
    washer: false,
    elevator: true,
    images: [],
  },
];
